# Generated by Django 4.2.6 on 2023-10-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Dog',
        ),
    ]
