# Generated by Django 4.2.2 on 2023-10-17 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(default='__init__', on_delete=django.db.models.deletion.CASCADE, related_name='DogBreed', to='dogs.breed'),
        ),
    ]
